### ISSUE TITLE
Searching on localhost doesn't work

### ISSUE THREAD

**Issue by cyt3ea** [thecourseforum/theCourseForum#101]
Searched CS 4810 on localhost
![screenshot from 2015-04-06 22 37 21](https://cloud.githubusercontent.com/assets/9666592/7016202/a325878a-dcad-11e4-9feb-9b62fb077810.png)

**Comment by aw3as** [comment]
Search functionality should be tested using beta.thecourseforum.com as that has a live Solr server which handles search.
