### ISSUE TITLE
Dump reviews for a semester with associated sis_class_number, section, and semester

### ISSUE THREAD

**Issue by ama4tf** [thecourseforum/theCourseForum#102]

**Comment by emumoo** [comment]
For the import, should the existing reviews be deleted before importing?

**Comment by aw3as** [comment]
no need we can truncate that table when we rerun

**Comment by emumoo** [comment]
okay

**Comment by emumoo** [comment]
Done!

*edited professor.course_list to not sort because call to mnemonic caused an error.
