### ISSUE TITLE
'Was this review helpful?' should be left aligned

### ISSUE THREAD

**Issue by sneelz** [thecourseforum/theCourseForum#105]
'Was this review helpful?' and the 'yes' and 'no' buttons should be left aligned with the left edge of the actual review comment/text. Also, the space between the 'Was this review helpful?' and the buttons should not stretch with the page.

![image](https://cloud.githubusercontent.com/assets/11659471/7104416/f96074ee-e0ad-11e4-844c-1f1b1d266386.png)

**Comment by cyt3ea** [comment]
There is already a "_ out of _ people found this helpful" if the review has been voted up or down. 

![screenshot from 2015-04-13 22 13 12](https://cloud.githubusercontent.com/assets/9666592/7129142/4f519158-e22a-11e4-803b-9b879645e02a.png)

**Comment by aw3as** [comment]
fixed via upvote/downvote ala reddit
