### ISSUE TITLE
Change cumulative grades pie chart colors

### ISSUE THREAD

**Issue by sneelz** [thecourseforum/theCourseForum#107]
New color codes are:

A+: #223165
A: #15214B
A-: #0F1932
B+: #EE5F35
B: #D75626
B-: #C14927
C+: #5A6D8E
C: #4D5C7C
C-: #3E4968
Other: #9F9F9F

![image](https://cloud.githubusercontent.com/assets/11659471/7104445/498b05a0-e0af-11e4-9206-6a40b24ff234.png)

**Comment by zeizyy** [comment]
Change color of the pie chart.
