### ISSUE TITLE
Decrease sidebar font size by 2pt

### ISSUE THREAD

**Issue by sneelz** [thecourseforum/theCourseForum#108]
I'm not sure what font size the sidebar text is at now, but decrease it by about 2pts. Also decrease the distance between the horizontal lines to 60px (I believe they're at 67px now). That should make it look a bit better on smaller screen resolutions.

![image](https://cloud.githubusercontent.com/assets/11659471/7104469/9f87f286-e0b1-11e4-9ddf-d604419ab7fd.png)

**Comment by aw3as** [comment]
fixed via 46db342
