### ISSUE TITLE
Get rid of orange container box around logo on homepage

### ISSUE THREAD

**Issue by sneelz** [thecourseforum/theCourseForum#109]
Only on the homepage, get rid of the orange box in the top left corner containing the logo. I can send a different version of the logo with different font colors, but I think getting rid of the orange box will make the homepage look better.

![image](https://cloud.githubusercontent.com/assets/11659471/7104507/6dcda436-e0b4-11e4-824f-891713629e8b.png)

**Comment by aw3as** [comment]
fixed in redesign-3.5
