### ISSUE TITLE
Statement Invalid in Courses Controller

### ISSUE THREAD

**Issue by cyt3ea** [thecourseforum/theCourseForum#113]
Browse All
Click Computer Science
Click CS 1110
Error page shows up
![screenshot from 2015-04-30 23 41 42](https://cloud.githubusercontent.com/assets/9666592/7426412/9628eeee-ef92-11e4-84c5-82286203774c.png)

**Comment by aw3as** [comment]
pull most recent beta database from phpmyadmin
