### ISSUE TITLE
Redesign course page

### ISSUE THREAD

**Issue by msukkar** [thecourseforum/theCourseForum#121]
The course page can benefit from a redesign. Currently has an excess amount of white-space. The radio buttons leave a lot of white space for courses with a smaller number of professors. 
- [x] Remove the background container and transition to separate panes
- [x] Header 
- [x] Stats boxes
- [x] Grade wheel 
- [x] Textbooks
- [x] Reviews

**Comment by keenadams** [comment]
We need to fix the routing and controller so that it links from the professor browse page and will load up that professors data rather than just overall
