### ISSUE TITLE
Make the beta site responsive

### ISSUE THREAD

**Issue by msukkar** [thecourseforum/theCourseForum#124]
The beta site is currently all but unusable on mobile. We need to make improvements on this before launch

**Comment by msukkar** [comment]
Beyond just mobile, this addresses a larger use case: snapping the window to a side. When I'm using theCourseForum, I'm typically also browsing lou's list or filling in courses on sis and want to view both side by side. 

Current state:

 - [ ] Course Scheduler page is clunky
![untitled](https://cloud.githubusercontent.com/assets/5864913/8096701/dbeef236-0fa7-11e5-84d5-15cc98d71c19.png)
)

 - [ ] Navigation is disabled (button does nothing)
![image](https://cloud.githubusercontent.com/assets/5864913/8096600/f5119bca-0fa6-11e5-9ab8-e3634435b081.png)

 - [ ] Workload spills over
![image](https://cloud.githubusercontent.com/assets/5864913/8096620/378220f6-0fa7-11e5-87f1-0f50938b36fe.png)

 - [ ] Highchart formatting is off
![image](https://cloud.githubusercontent.com/assets/5864913/8096635/53f45ac4-0fa7-11e5-8055-9a2328fac7ac.png)

**Comment by aw3as** [comment]
fixed via 3.0
