### ISSUE TITLE
Inconsistent behavior for professors without grades

### ISSUE THREAD

**Issue by keenadams** [thecourseforum/theCourseForum#133]
Even though the professor doesn't have a "has grades" icon, a highcharts graph will still appear with the overall grades stats. These grades stats will also appear on the course page. Even when the highcharts graph doesn't appear for a professor, the overall gradewheel will still sometimes appear on their course page.

**Comment by atallahhezbor** [comment]
1) Do you mean the empty highcharts graph? I can't find an example where the icon isn't there but the grade bar has data.
2) It seems like the gradewheel on the course page still reflects the overall course and not the professor's section. Didn't @aw3as fix that?

**Comment by keenadams** [comment]
1) I was looking specifically at AAS 4570. Several of the professors have grades but then some of them don't and are overlapping and it's all just pretty weird. Like Hays and Gaines have different highcharts bars but the same GPA number. But their course pages have the same grade wheel.
2) We fixed the redirect to the course page so it includes the professor id. That changed the review data so that it applied to the professor. But yeah the gradewheels are definitely not right so I'll look into that. It's probably a matter of changing some logic somewhere.

**Comment by atallahhezbor** [comment]
Oh! Yeah I see it. In the course show page it's calling get grade percentages without passing in an id so it's getting all of them.
