### ISSUE TITLE
Lavender logo background?

### ISSUE THREAD

**Issue by sneelz** [thecourseforum/theCourseForum#142]
The redesign looks so awesome!! I really like that you guys took out the department professors list and made filtering by professor part of the overall browse process, it definitely flows much better. Is a professor info page going to be added to the site in future updates? Maybe that information could go on the course professors list info bar.

I was kind of surprised by the lavender logo background since I don't really think of lavender when I think of theCourseForum. If orange (#d75626) is a bit too strong, I think that the light blue accent color (#6c8ac1) would look nice. I attached the orange and blue bubble variations of the white text logo.

![image](https://cloud.githubusercontent.com/assets/11659471/8968740/27e78136-360d-11e5-949c-999b9b481c49.png)
![image](https://cloud.githubusercontent.com/assets/11659471/8968741/2baddd74-360d-11e5-852a-5cb8fcd2da3d.png)
![image](https://cloud.githubusercontent.com/assets/11659471/8968787/712145f8-360d-11e5-98b6-fbec606cb7eb.png)

![tcf-logo-white-blue](https://cloud.githubusercontent.com/assets/11659471/8968816/a97e306e-360d-11e5-82cb-71ee410cad85.png)
![tcf-logo-white-orange](https://cloud.githubusercontent.com/assets/11659471/8968817/a97eeeb4-360d-11e5-89a7-d42ae845e73d.png)

**Comment by keenadams** [comment]
We were trying to go for a color where it looked like the sidebar went under the header. I changed it to #f1f6fb which I think is more grey/blue? Does that look better? 

Eventually I think we're going to change the sidebar where it's collapsible and there'll be a button next to the logo that expands it. So the current version is temporary.

**Comment by sneelz** [comment]
I feel like if you're going that light of a logo background color, you might as well just use the gray color (#eeeded). I attached some color options for the collapsible sidebar + header if/when they are being changed in the future. For a white header, I added a 1px bottom border of #d1d2d4.

On a side note, I'm compiling mockups/style guides/logos/etc. into a folder that I'll upload to Slack for future use and reference.

![tcf-color-5](https://cloud.githubusercontent.com/assets/11659471/9013790/2f51d414-378c-11e5-9840-a2fad7fd8c4a.jpg)
![tcf-color-3](https://cloud.githubusercontent.com/assets/11659471/9013792/2f54cfca-378c-11e5-8925-d184804c7eee.jpg)
![tcf-color-4](https://cloud.githubusercontent.com/assets/11659471/9013791/2f53fa28-378c-11e5-8636-95ff1fe6912b.jpg)
![tcf-color-1](https://cloud.githubusercontent.com/assets/11659471/9013794/2f55f544-378c-11e5-8c30-ff74f2ea5b0e.jpg)
![tcf-color-2](https://cloud.githubusercontent.com/assets/11659471/9013793/2f55aaee-378c-11e5-845e-5fad3218bc69.jpg)
