### ISSUE TITLE
Review text does not stay within content div if a string of text is longer than the max-width

### ISSUE THREAD

**Issue by sneelz** [thecourseforum/theCourseForum#149]
Check out the first review on this page to see what I mean: http://thecourseforum.com/courses/84?p=51
The width of the upvote/downvote button area is also affected by this
Maybe it's something that has to be manually edited on the individual's review

**Comment by keenadams** [comment]
haha that link is wack. 
I've got a fix for it figured out so now I'm just waiting on alan to get to pushed to live
