### ISSUE TITLE
Realign 'My Account' entry boxes

### ISSUE THREAD

**Issue by sneelz** [thecourseforum/theCourseForum#156]
Realign the 'Last name' and 'Confirm new password' entry boxes to be in line with the 2nd column, rather than horizontally stretch based on the screen width

![image](https://cloud.githubusercontent.com/assets/11659471/9093776/0c0b3510-3b7c-11e5-9e67-cfb8174eb69e.png)

**Comment by NikashS** [comment]
This has been fixed, it is realigned now.
