### ISSUE TITLE
make certain pages public (for amazon)

### ISSUE THREAD

**Issue by aw3as** [thecourseforum/theCourseForum#173]
in order to pass amazon review, we need to open up a few pages for amazon, such as econ 2010 or maybe cs 2150?

**Comment by keenadams** [comment]
we probably want to do econ 2010 because 2150 doesn't have any books.

**Comment by aw3as** [comment]
can we get a short list of classes then? i'm thinking maybe 5-9

**Comment by emumoo** [comment]
some options

| title | course id | review count | book count |

| Principles of Economics: Microeconomics  | 1642 | 701 |  4 |
| Principles of Economics: Macroeconomics  | 1643 | 467 |  2 |
| Introduction to the Sky and Solar System |  570 | 229 |  3 |
| Multivariable Calculus                   |  204 | 169 |  1 |
| Introductory College Chemistry           | 1013 | 168 |  2 |
| Intermediate Microeconomics              | 1646 | 167 |  5 |
| Commercial Law I                         | 1231 | 161 |  2 |
| Organic Chemistry                        | 1027 | 155 |  9 |
| Single Variable Calculus II              |  203 | 154 |  2 |
| Cell Biology                             |  692 | 134 |  2 |
| Intermediate Macroeconomics              | 1647 | 132 |  2 |
| Accelerated Academic Writing             | 2349 | 123 | 40 |
| Software Development Methods             | 1321 | 123 |  1 |
| Ordinary Differential Equations          |  205 | 117 |  1 |

**Comment by emumoo** [comment]
alternatively, these are classes with most books associated

| title                                                  | course id | review count | book count |
+--------------------------------------------------------+------+-----+----+
| College Advising Seminars                              | 1212 |  47 | 78 |
| Studies in Poetry                                      | 2251 |   7 | 47 |
| Special Topics                                         | 2258 |  22 | 41 |
| Accelerated Academic Writing                           | 2349 | 123 | 40 |
| Studies in Modern and Contemporary Literature          | 2266 |   2 | 19 |
| Nineteenth Century Topics                              | 2299 |   1 | 18 |
| Studies in Fiction                                     | 2253 |   6 | 16 |
| Masterworks of Literature                              | 2201 |   2 | 15 |
| Advanced Studies in Nineteenth Century Literature I    | 2303 |   7 | 15 |
| Narratives of Illness and Doctoring                    | 2334 |   1 | 12 |
| The Fiction of Empire                                  | 2302 |   1 | 12 |
| History of European Literature I                       | 2202 |   1 | 11 |
| Introductory Seminar in Post-1700 European History     | 3180 |   5 | 11 |
| History of European Literature I                       | 1300 |   9 | 11 |
| Advanced Studies in Modern and Contemporary Literature | 2271 |   4 | 10 |
| Greek Civilization                                     | 1196 |  23 |  9 |
| Organic Chemistry                                      | 1027 | 155 |  9 |
| Theory and History of Anthropology                     |  111 |   8 |  9 |
| The Fall of the Roman Republic                         | 3196 |   1 |  8 |
| The Literature of the South                            | 2165 |  10 |  8 |

**Comment by aw3as** [comment]
closed via 0aefdb8cd214f8857c066127607c15c9e830e8e3
