### ISSUE TITLE
Make About Page more stunning

### ISSUE THREAD

**Issue by cyt3ea** [thecourseforum/theCourseForum#175]

**Comment by aw3as** [comment]
something like radical's about us, http://thisisradical.com/about-us/ or http://www.coshx.com/about/

**Comment by cyt3ea** [comment]
I was also thinking something like this - http://kpcbfellows.com/meet-the-fellows
Do we want blurbs about ourselves or are we just going for name and position.

**Comment by DC00** [comment]
new branch: 'about'

**Comment by keenadams** [comment]
Can you assign @tlk2dq to this? She can design the layout for you guys.

**Comment by cyt3ea** [comment]
I don't see her on the list to add as assignee but yeah I'll talk to her about it.

**Comment by aw3as** [comment]
assigned - tati can you take a look?

**Comment by tlk2dq** [comment]
Yea I'll take a look this weekend!
