### ISSUE TITLE
add version number somewhere (preferably link to blog)

### ISSUE THREAD

**Issue by aw3as** [thecourseforum/theCourseForum#176]
need to add version number below the Privacy | Terms | theCourseForum copyright. something like v3.0.1

**Comment by DC00** [comment]
Branched beta. Trying to understand the workflow. There should be a new pull request?
git push origin beta:[name of branch]    --> is this correct?

**Comment by DC00** [comment]
Nevermind
git push --set-upstream origin 176-version-number

**Comment by aw3as** [comment]
BRANCH OFF OF MASTER NOT BETA

**Comment by DC00** [comment]
OKAY
