### ISSUE TITLE
Clean Up Professor Page

### ISSUE THREAD

**Issue by kienan** [thecourseforum/theCourseForum#213]
I'm thinking changing it up to something close to this wireframe.
![professor_page](https://cloud.githubusercontent.com/assets/5743276/10870322/b64555b6-8095-11e5-842c-6d8650f77f53.png)

**Comment by atallahhezbor** [comment]
https://github.com/thecourseforum/theCourseForum/commit/97f48d4c6a0387066cff28790e6e53768bbcb216
