### ISSUE TITLE
Explanation for no grades

### ISSUE THREAD

**Issue by msukkar** [thecourseforum/theCourseForum#217]
It would be nice if we had an explanation on pages with no grades. Something along the lines of: "We're sorry but there are no grades available for this class. This could happen due to 2 reasons: 1. UVA determined releasing grades for this course would allow identification of what grade a given student received or 2. this professor/course combo has not occurred in any previous semesters."

**Comment by lpj2jg** [comment]
Great idea.  I hear complaints all the time, "Lewis why are there no grades
for XXXX class?"

Lewis

**Comment by seanbspector** [comment]
I totally agree. It’s a lot easier than having to explain it ourselves.

Maybe we should also have a message when there are no reviews. I have had so many people ask me why there are no reviews for classes, and then I ask them if they have ever written a review and they quickly understand where I am going with the conversation…
