### ISSUE TITLE
Redesign my reviews stats 

### ISSUE THREAD

**Issue by cyt3ea** [thecourseforum/theCourseForum#292]
Go to my_reviews branch and improve the stats design at the top
- Add anymore stats you think would be good to have
- Make sure the button to 'Write Another Review' is obvious and clear, this is to encourage people to write another review after submitting a review
- Make sure if a user does not have any reviews, there is a placeholder telling the user that they don't have any reviews and shouuld write one

**Comment by josie-chiao** [comment]
Was decided that the stats design is fine, small wording changes made. See commit: https://github.com/thecourseforum/theCourseForum/commit/44fd34efb4554cded3f260e686908a1dba0bd305

**Comment by josie-chiao** [comment]
Was decided that the stats design is fine, small wording changes made. See commit: https://github.com/thecourseforum/theCourseForum/commit/44fd34efb4554cded3f260e686908a1dba0bd305
