### ISSUE TITLE
Fix modal positioning

### ISSUE THREAD

**Issue by cyt3ea** [thecourseforum/theCourseForum#295]
Modals for feedback, how to use the scheduler, etc, should be centered and not cut off:

![image](https://cloud.githubusercontent.com/assets/9666592/23928509/80984af0-08f6-11e7-8200-4e05fdbbbc6d.png)

**Comment by cpark11** [comment]
Does this bug occur on feedback as well, b/c on my computer it only seems to happen on the "how to use" for the scheduler.

**Comment by cpark11** [comment]
textbook sell modal needs work - on the larger side

**Comment by cpark11** [comment]
clicking very far outside how-to-modal is not so great
