### ISSUE TITLE
Rails Error Page

### ISSUE THREAD

**Issue by clgy15** [thecourseforum/theCourseForum#34]
This doesn't help our users. At least say, theCourseForum had an issue. Uh Oh!

![this](https://cloud.githubusercontent.com/assets/1672876/6234666/a7145f5c-b6aa-11e4-8aaa-169bdb4ff469.png)

**Comment by aw3as** [comment]
Static HTML file located in public -> 500.html. If we want, we can just create static HTML files for 404, 422, and 500 errors to provide more information.

**Comment by clgy15** [comment]
Simple to do then, probably some intro exercise we can do this week or next with the new recruits
