### ISSUE TITLE
Tagging for classes

### ISSUE THREAD

**Issue by ama4tf** [thecourseforum/theCourseForum#35]
This was proposed by an applicant and merits discussion. Would need database restructuring and a slight change to the front-end to handle this, but could be a cool feature

**Comment by jt4uc** [comment]
That was me! I think it's a great idea. I'm not biased. Lou's list has pages for some Arts and Sciences requirements, but major requirements in general and other categories of classes are unmarked. How would we go about grabbing all that data?

**Comment by aw3as** [comment]
bring this up during our sunday meetings - we will discuss then
