### ISSUE TITLE
Fix mobile login page on beta

### ISSUE THREAD

**Issue by ama4tf** [thecourseforum/theCourseForum#36]
The login on android devices is pretty rough often blocking the textboxes required to log in

![login mobile](https://cloud.githubusercontent.com/assets/5315159/6426754/ec5a5d42-bf37-11e4-9846-1933dd7b1f31.png)

**Comment by msukkar** [comment]
This has been handled.
![image](https://cloud.githubusercontent.com/assets/5864913/10417627/ae994358-7010-11e5-8dbf-260811ed22c6.png)
