### ISSUE TITLE
Cannot choose the specific course in 'Write a Review'

### ISSUE THREAD

**Issue by zeizyy** [thecourseforum/theCourseForum#38]
In 'Write a Review', you cannot choose the course and the professor after you choose the department.

**Comment by atallahhezbor** [comment]
Take a look in controllers/review_controller.rb 
specifically the new method there
and
views/reviews/new.html.slim
which uses _form.html.slim

**Comment by aw3as** [comment]
CTRL-SHIFT-I on Chrome will open up the Inspector - use this to see what network requests are going on when you choose a department.

**Comment by Apoorva-A** [comment]
Added missing line of code to routes.rb "resources :subdepartments, :only => [:show]" in order to show the courses and professors for a specific course when writing reviews.
