### ISSUE TITLE
Grade Distrubtions Chart not Showing up

### ISSUE THREAD

**Issue by Apoorva-A** [thecourseforum/theCourseForum#40]
After searching by professor, the grade distribution charts are not showing up for some of the linear algebra courses taught by Abramenko and Holt

**Comment by Apoorva-A** [comment]
So I went to search by professor, A, Abramenko, and no grade distributions showed up when i clicked on the 3080 class when they should

**Comment by aw3as** [comment]
verify if professor page comes from course_professors, or if graph still doesn't show on courses page for a specific professor. if issue is fixed, close issue

**Comment by jt4uc** [comment]
Browsing by course shows the graph, but browsing by professor does not (until you refresh)

**Comment by aw3as** [comment]
turbolinks issue - verify if fixed

**Comment by msukkar** [comment]
I believe this is now fixed. Reopen if that's not the case.
