### ISSUE TITLE
The 'yes' and 'no' for 'Was this review helpful?' is not functional

### ISSUE THREAD

**Issue by zeizyy** [thecourseforum/theCourseForum#41]
For APMA 3080 at lease if you go from 'browse by professor' and the interface is slightly messed up.

**Comment by atallahhezbor** [comment]
This only happens when the course is reached by browsing by professor????? :O

**Comment by atallahhezbor** [comment]
http://beta.thecourseforum.com/course_professors?c=1322&p=616
vs
http://beta.thecourseforum.com/courses/1322

**Comment by zeizyy** [comment]
modified  app/views/course_professors/index.html.slim and app/views/courses/show.html.slim. Most of the changes are format issue.
1. In index.html.slim,
-        ul.meta
-          li= r.created_at.strftime("%Y-%m-%d")
+        .col-xs-2
+          = r.created_at.strftime("%Y-%m-%d")
2. In index.html.slim
-        .comment
-          = h(r.comment).gsub(/\n/, '<br/>').html_safe
-        ul.ratings.visible-md.visible-lg
-          li.overall= r.overall
-          li.professor_rating= r.professor_rating
-          li.enjoyability= r.enjoyability
-          li.difficulty= r.difficulty
-          li.recommend= r.recommend
+        .col-xs-8
+          .comment
+           = h(r.comment).gsub(/\n/, '<br/>').html_safe
+        .col-xs-2
+          ul.ratings.visible-md.visible-lg
+            .row
+              .col-xs-12
+                span.rating-icon= image_tag "icons/heart.png"
+                = r.overall
+            .row
+              .col-xs-12
+                span.rating-icon= image_tag "icons/user_gray.png"
+                = r.professor_rating
+            .row
+              .col-xs-12
+                span.rating-icon= image_tag "icons/emoticon_smile.png"
+                = r.enjoyability
+            .row
+              .col-xs-12
+                span.rating-icon= image_tag "icons/user_comment.png"
+                = r.difficulty
+            .row
+              .col-xs-12
+                span.rating-icon= image_tag "icons/pencil.png"
+                = r.recommend
Basically, I add icon to 'Overall', 'Professor' etc. and change the format

3. In the same file
-            = r.votes_for
-            | out of
-            = r.votes_count
-            | people found this helpful.
-        .col-xs-3 style="margin-top: 2.5px;"
-          .rating style="font-size:12px;text-align:center;"
-            | Was this review helpful?
-        .col-xs-2.col-sm-1
-          .btn.btn-primary.btn-xs id="vote_up_#{r.id}" style="#{'font-size:12px;text-align:center;' + (current_user.voted_against?(r) ? 'opacity: 0.4;' : '')}" disabled=
-            | Yes
-        .col-xs-2.col-sm-1
-          .btn.btn-primary.btn-xs id="vote_down_#{r.id}" style="#{'font-size:12px;text-align:center;' + (current_user.voted_for?(r) ? 'opacity: 0.4;' : '')}" disabled="#
-            | No
+            = "#{r.votes_for} out of #{r.votes_count} people found this helpful."
+        - if r.user != current_user
+          .col-xs-3 style="margin-top: 2.5px;"
+            .rating style="font-size:12px;text-align:center;"
+              | Was this review helpful?
+          .col-xs-2.col-sm-1
+            .btn.btn-primary.btn-xs id="vote_up_#{r.id}" style="#{'font-size:12px;text-align:center;' + (current_user.voted_against?(r) ? 'opacity: 0.4;' : '')}" disable
+              | Yes
+          .col-xs-2.col-sm-1
+            .btn.btn-primary.btn-xs id="vote_down_#{r.id}" style="#{'font-size:12px;text-align:center;' + (current_user.voted_for?(r) ? 'opacity: 0.4;' : '')}" disabled=
+              | No
Change to match the app/views/courses/show.html.slim

4.
-              .btn.btn-primary.btn-xs id="vote_up_#{r.id}" style="#{'font-size:12px;text-align:center;' + (current_user.voted_against?(r) ? 'opacity: 0.4;' : '')}" 
+              .btn.btn-primary.btn-xs id="vote_up_#{r.id}" style="#{'font-size:12px;text-align:center;' + (current_user.voted_against?(r) ? 'opacity: 0.4;' : '')}" disab
                 | Yes
             .col-xs-2.col-sm-1
-              .btn.btn-primary.btn-xs id="vote_down_#{r.id}" style="#{'font-size:12px;text-align:center;' + (current_user.voted_for?(r) ? 'opacity: 0.4;' : '')}"
+              .btn.btn-primary.btn-xs id="vote_down_#{r.id}" style="#{'font-size:12px;text-align:center;' + (current_user.voted_for?(r) ? 'opacity: 0.4;' : '')}" disable
                 | No
-    = will_paginate @reviews
+  = will_paginate @reviews
