### ISSUE TITLE
Inconsistent user interface to switch between professors and inconsistent reviews when on a specific class page

### ISSUE THREAD

**Issue by cyt3ea** [thecourseforum/theCourseForum#44]
Selecting a class by professor gives a drop-down menu to browse between professors and the reviews do not show all the information like in the old course forum (review is formatted weirdly, lists bullet points without saying what category the rating is for, etc.)
Selecting a class from the front page menu (browsing by categories) gives a multiple-choice like bar on the side to browse between professors. Reviews looks good though when selecting a class this way though.

**Comment by aw3as** [comment]
related to old course_professors page, should be removed now. all new course pages with professors should look formatted - close issue if you can't find anymore examples of bad formatting
