### ISSUE TITLE
Cannot submit a review

### ISSUE THREAD

**Issue by zeizyy** [thecourseforum/theCourseForum#46]
The website complains that 
    Professor rating must be greater than or equal to 1
    Enjoyability must be greater than or equal to 1
    Difficulty must be greater than or equal to 1
    Recommend must be greater than or equal to 1
However all the fields are greater than 1

**Comment by ama4tf** [comment]
Can you append a screenshot or a specific url and actions to recreate the bug?

**Comment by jt4uc** [comment]
Duplicate of #64
