### ISSUE TITLE
The site doesn't run on firefox 3.1?

### ISSUE THREAD

**Issue by Marcus-Rosti** [thecourseforum/theCourseForum#50]
Is there any chance you guys will be able to support this?

**Comment by jt4uc** [comment]
Firefox is up to 37.0.1 now...?

**Comment by atallahhezbor** [comment]
We need to account for our diverse user base

**Comment by JustinDao** [comment]
Can I +1 issue comments?

**Comment by Marcus-Rosti** [comment]
Thanks for dealing with this issue.  It's the only version that RedHat and CentOS really support
