### ISSUE TITLE
Can't sort comments based on most helpful/most recent etc.

### ISSUE THREAD

**Issue by jt4uc** [thecourseforum/theCourseForum#51]
When there are reviews, no drop down bar shows up to sort comments. This is key functionality that is missing in the redesign but present in the current website.

**Comment by aw3as** [comment]
Fundamentally - this is a difference in views between the redesign and beta branches. Be careful what view you are actually loading - course_professors or course? This functionality does exist in the redesign - but it's not where you're currently looking for. Redesign has a new "overall course" page - where is the current "sort by" functionality in redesign? (it exists somewhere)

**Comment by aw3as** [comment]
relevant files to look into:
app/views/course/show.html.slim
app/views/course_professors/index.html.slim
