### ISSUE TITLE
Visibility of Percentages

### ISSUE THREAD

**Issue by Apoorva-A** [thecourseforum/theCourseForum#52]
I know that you all changed the percentage values on the pie charts to be separate from the actual pie chart, but I would like to comment that it is easier in my opinion for the user to just view the percentages on the chart.

**Comment by aw3as** [comment]
could fold into graphics rework with interactive functionality - hover could show additional statistics. something you want to work on?

**Comment by msukkar** [comment]
Hover now shows percentages
