### ISSUE TITLE
Can't write a review when viewing a specific course page

### ISSUE THREAD

**Issue by jt4uc** [thecourseforum/theCourseForum#53]
Does not meet the objective of theCourseForum lol. Ex. CS 1110 course page does not show a write a review button.

**Comment by aw3as** [comment]
needs design input from graphics to determine view layout - where to put such a button. also to consider - saving that specific course as well for use in the scheduler.

**Comment by clgy15** [comment]
I think this is tied with our view is too 'Busy'. I agree with @aw3as, lets sit down with graphics to get this paged fixed up. Maybe tabs?
