### ISSUE TITLE
Have to refresh the page in order to show rating sliders

### ISSUE THREAD

**Issue by DC00** [thecourseforum/theCourseForum#55]
Before and after refreshing the page
![nosliders](https://cloud.githubusercontent.com/assets/5743301/6427459/7965eac8-bf4f-11e4-9619-ae4be8705745.png)

![after](https://cloud.githubusercontent.com/assets/5743301/6427461/825f51e6-bf4f-11e4-9569-299c8d3bc536.png)

1. Browse By Department
2. Clicked Random Course
3. Clicked Random Professor
4. Clicked "Write a Review"

**Comment by jt4uc** [comment]
Also doesn't show when editing a review you' written.

**Comment by aw3as** [comment]
This is a turbolinks issue - Justin coded in an exception for this case when you select "Write a Review" on the left side - see app/views/layout/_navigation.html.slim - something like data-no-turbolink. How can we apply this to Write a Review when accessing from the professor page?

**Comment by JustinDao** [comment]
Just give the link_to the attribute with a blank value.

`link_to "Write A Review", new_review_path, p: professor_id, c: course_id, "data-no-turbolink" => ""`

**Comment by jt4uc** [comment]
Writing a review for a class that doesn't have any reviews loads a page missing the sliders. Refreshing the page enables them again.

**Comment by aw3as** [comment]
Turbolinks issue - apply same fix as other turbolink issues
