### ISSUE TITLE
"Write a Review for this Course" for a class selected by browsing by professor issues

### ISSUE THREAD

**Issue by cyt3ea** [thecourseforum/theCourseForum#56]
When selecting a class by browsing by professor, there is a write a review for this class button unlike when you browse by categories, etc (though the placement of the buttons are weird). When clicked, the sliding bars to choose fun factor, difficulty, etc do not show up when the button is clicked. However if you submit it with everything filled out, the buttons will appear again as the page redirects you to the same write a review page because there were no values for the "grade the course" category. 

Also, if you just submit an empty review form, it takes you to an error page that shows code and says NoMethodError. Probably would be better if something just popped up and said you need to fill out the required forms.

**Comment by atallahhezbor** [comment]
Take a look in the views/course_professors/index.html.slim and maybe controllers/course_professors_controller.rb
