### ISSUE TITLE
Repeated Professors in Database

### ISSUE THREAD

**Issue by DC00** [thecourseforum/theCourseForum#63]
Go to:
Home Page -> E-school -> Chemical Engineering -> Professor's Tab

Robert Davis is repeated, and the courses in the second instance of Robert Davis are out of order. "O, John" and "O'Connell, John" are the same person I think

**Comment by aw3as** [comment]
professor database needs to be cleaned up - hand over to data. alex, thoughts? you can assign

**Comment by ama4tf** [comment]
Lol. I guess we can throw this in as an issue under project_blake, or fix these on a professor by professor issue

**Comment by aw3as** [comment]
moved
