### ISSUE TITLE
NaN for classes with no reviews

### ISSUE THREAD

**Issue by emumoo** [thecourseforum/theCourseForum#66]
I've noticed this occasionally for classes with no reviews.

![image](https://cloud.githubusercontent.com/assets/6572030/6431065/4f2c5e02-bff1-11e4-8040-b89e627909e4.png)

**Comment by emumoo** [comment]
A similar issue has been closed but I'm still noticing it sometimes

**Comment by aw3as** [comment]
can't reproduce in v3.0
