### ISSUE TITLE
Scheduler class times not updated

### ISSUE THREAD

**Issue by jt4uc** [thecourseforum/theCourseForum#82]
CS 3205 is listed as MoWe 3:30PM - 4:45PM on Lou's List/SIS but MoWe 2:00PM - 3:15PM on Scheduler
CS 4630 is listed as MoWeFr 9:00AM - 9:50AM on Lou's List/SIS but TuTh 12:30PM - 1:45PM on Scheduler
ENCW 3610 triggers an improper search error

Even uvaschedule.me doesn't have this problem :P

**Comment by aw3as** [comment]
most sections are in - test on beta.thecourseforum.com - Lou's List changes quickly on day-to-day basis so we don't have the ENCW courses in yet but others are correct.

**Comment by aw3as** [comment]
moved to project_blake
