### ISSUE TITLE
Scheduler courses sis id

### ISSUE THREAD

**Issue by emumoo** [thecourseforum/theCourseForum#85]
Since sis does look up by class number when enrolling, it would be good if it was provided on the scheduler

**Comment by emumoo** [comment]
The numbers could be hidden somewhere since they are only useful while enrolling/dealing with SIS

**Comment by atallahhezbor** [comment]
Anyone who wants to take this one up could look into making it a hover action 
http://www.w3schools.com/jquery/event_hover.asp
Shoiuldn't be too bad! I believe the info is already part of the JS section object

**Comment by aw3as** [comment]
fixed via fd8557a
