### ISSUE TITLE
Stretch: Ideas for Recommendations Page

### ISSUE THREAD

**Issue by DC00** [thecourseforum/theCourseForum#89]
The Recommendations page "should be like a custom search for unique college classes. I always wanted to find cool classes in the college but never knew where to look." - My friend

Ideas
- Choose a department, sort by highest average grade. Filters for average grade, professor rating, time spent reading/hw, likeability
- Manually enter "Staff Recommendations" - our favorite classes

**Comment by atallahhezbor** [comment]
Ooo I like that

maybe also scrape reviews for "i'd recommend this course if"?

We could eventually flesh this out into more of a "Finding a course to take" which would be much more narrowed down as opposed having to browse through everything.

**Comment by seanbspector** [comment]
Great idea Daniel.

That is exactly what we are going for, a way to make find classes easier to
find.

We could also have it present classes to you that other people in your
major/year have been looking at or classes they have reviewed positively.

**Comment by aw3as** [comment]
needs to discussed more during sunday meetings before we escalate to github issue
