### ISSUE TITLE
Browse by professor looks funky

### ISSUE THREAD

**Issue by cyt3ea** [thecourseforum/theCourseForum#99]
Browse by professor
Selected letter A
Selected Abramenko, Monika
Text on professor page overlaps with professor average rating
![screenshot from 2015-04-06 22 20 27](https://cloud.githubusercontent.com/assets/9666592/7016007/27f4a156-dcab-11e4-9476-a27e45381eee.png)

**Comment by DC00** [comment]
Christine's resolution is messed up. Could not recreate
